// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/contract.proto

/*
Package wxvm is a generated protocol buffer package.

It is generated from these files:
	pb/contract.proto

It has these top-level messages:
	ArgPair
	CallArgs
	PutRequest
	PutResponse
	GetRequest
	GetResponse
	DeleteRequest
	DeleteResponse
	IteratorRequest
	IteratorItem
	IteratorResponse
	Response
	SetOutputRequest
	SetOutputResponse
	GetCallArgsRequest
	LogMsgRequest
	LogMsgResponse
	ContractCallRequest
	ContractCallResponse
*/
package xvm

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ArgPair struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *ArgPair) Reset()                    { *m = ArgPair{} }
func (m *ArgPair) String() string            { return proto.CompactTextString(m) }
func (*ArgPair) ProtoMessage()               {}
func (*ArgPair) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ArgPair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ArgPair) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type CallArgs struct {
	Args []*ArgPair `protobuf:"bytes,1,rep,name=args" json:"args,omitempty"`
}

func (m *CallArgs) Reset()                    { *m = CallArgs{} }
func (m *CallArgs) String() string            { return proto.CompactTextString(m) }
func (*CallArgs) ProtoMessage()               {}
func (*CallArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CallArgs) GetArgs() []*ArgPair {
	if m != nil {
		return m.Args
	}
	return nil
}

type PutRequest struct {
	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *PutRequest) Reset()                    { *m = PutRequest{} }
func (m *PutRequest) String() string            { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()               {}
func (*PutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PutRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *PutRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type PutResponse struct {
}

func (m *PutResponse) Reset()                    { *m = PutResponse{} }
func (m *PutResponse) String() string            { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()               {}
func (*PutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type GetRequest struct {
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type GetResponse struct {
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type DeleteRequest struct {
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DeleteRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type IteratorRequest struct {
	Start []byte `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	Limit []byte `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cap   int32  `protobuf:"varint,3,opt,name=cap" json:"cap,omitempty"`
}

func (m *IteratorRequest) Reset()                    { *m = IteratorRequest{} }
func (m *IteratorRequest) String() string            { return proto.CompactTextString(m) }
func (*IteratorRequest) ProtoMessage()               {}
func (*IteratorRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *IteratorRequest) GetStart() []byte {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *IteratorRequest) GetLimit() []byte {
	if m != nil {
		return m.Limit
	}
	return nil
}

func (m *IteratorRequest) GetCap() int32 {
	if m != nil {
		return m.Cap
	}
	return 0
}

type IteratorItem struct {
	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *IteratorItem) Reset()                    { *m = IteratorItem{} }
func (m *IteratorItem) String() string            { return proto.CompactTextString(m) }
func (*IteratorItem) ProtoMessage()               {}
func (*IteratorItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *IteratorItem) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *IteratorItem) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type IteratorResponse struct {
	Items []*IteratorItem `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *IteratorResponse) Reset()                    { *m = IteratorResponse{} }
func (m *IteratorResponse) String() string            { return proto.CompactTextString(m) }
func (*IteratorResponse) ProtoMessage()               {}
func (*IteratorResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *IteratorResponse) GetItems() []*IteratorItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type Response struct {
	Code    int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Result  []byte `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

type SetOutputRequest struct {
	Response *Response `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
}

func (m *SetOutputRequest) Reset()                    { *m = SetOutputRequest{} }
func (m *SetOutputRequest) String() string            { return proto.CompactTextString(m) }
func (*SetOutputRequest) ProtoMessage()               {}
func (*SetOutputRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *SetOutputRequest) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

type SetOutputResponse struct {
}

func (m *SetOutputResponse) Reset()                    { *m = SetOutputResponse{} }
func (m *SetOutputResponse) String() string            { return proto.CompactTextString(m) }
func (*SetOutputResponse) ProtoMessage()               {}
func (*SetOutputResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type GetCallArgsRequest struct {
}

func (m *GetCallArgsRequest) Reset()                    { *m = GetCallArgsRequest{} }
func (m *GetCallArgsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetCallArgsRequest) ProtoMessage()               {}
func (*GetCallArgsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type LogMsgRequest struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *LogMsgRequest) Reset()                    { *m = LogMsgRequest{} }
func (m *LogMsgRequest) String() string            { return proto.CompactTextString(m) }
func (*LogMsgRequest) ProtoMessage()               {}
func (*LogMsgRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *LogMsgRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type LogMsgResponse struct {
}

func (m *LogMsgResponse) Reset()                    { *m = LogMsgResponse{} }
func (m *LogMsgResponse) String() string            { return proto.CompactTextString(m) }
func (*LogMsgResponse) ProtoMessage()               {}
func (*LogMsgResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type ContractCallRequest struct {
	Contract string     `protobuf:"bytes,1,opt,name=contract" json:"contract,omitempty"`
	Method   string     `protobuf:"bytes,2,opt,name=method" json:"method,omitempty"`
	Args     []*ArgPair `protobuf:"bytes,3,rep,name=args" json:"args,omitempty"`
}

func (m *ContractCallRequest) Reset()                    { *m = ContractCallRequest{} }
func (m *ContractCallRequest) String() string            { return proto.CompactTextString(m) }
func (*ContractCallRequest) ProtoMessage()               {}
func (*ContractCallRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *ContractCallRequest) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *ContractCallRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *ContractCallRequest) GetArgs() []*ArgPair {
	if m != nil {
		return m.Args
	}
	return nil
}

type ContractCallResponse struct {
	Response *Response `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
}

func (m *ContractCallResponse) Reset()                    { *m = ContractCallResponse{} }
func (m *ContractCallResponse) String() string            { return proto.CompactTextString(m) }
func (*ContractCallResponse) ProtoMessage()               {}
func (*ContractCallResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *ContractCallResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*ArgPair)(nil), "chainmaker.ArgPair")
	proto.RegisterType((*CallArgs)(nil), "chainmaker.CallArgs")
	proto.RegisterType((*PutRequest)(nil), "chainmaker.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "chainmaker.PutResponse")
	proto.RegisterType((*GetRequest)(nil), "chainmaker.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "chainmaker.GetResponse")
	proto.RegisterType((*DeleteRequest)(nil), "chainmaker.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "chainmaker.DeleteResponse")
	proto.RegisterType((*IteratorRequest)(nil), "chainmaker.IteratorRequest")
	proto.RegisterType((*IteratorItem)(nil), "chainmaker.IteratorItem")
	proto.RegisterType((*IteratorResponse)(nil), "chainmaker.IteratorResponse")
	proto.RegisterType((*Response)(nil), "chainmaker.Response")
	proto.RegisterType((*SetOutputRequest)(nil), "chainmaker.SetOutputRequest")
	proto.RegisterType((*SetOutputResponse)(nil), "chainmaker.SetOutputResponse")
	proto.RegisterType((*GetCallArgsRequest)(nil), "chainmaker.GetCallArgsRequest")
	proto.RegisterType((*LogMsgRequest)(nil), "chainmaker.LogMsgRequest")
	proto.RegisterType((*LogMsgResponse)(nil), "chainmaker.LogMsgResponse")
	proto.RegisterType((*ContractCallRequest)(nil), "chainmaker.ContractCallRequest")
	proto.RegisterType((*ContractCallResponse)(nil), "chainmaker.ContractCallResponse")
}

func init() { proto.RegisterFile("pb/contract.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 444 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xcb, 0x6f, 0xd4, 0x30,
	0x10, 0xc6, 0x15, 0xb2, 0x69, 0xd3, 0xd9, 0x2d, 0x6c, 0xb3, 0x11, 0x8a, 0x38, 0xa0, 0xc5, 0x1c,
	0xd8, 0xd3, 0x02, 0x2d, 0xe2, 0xde, 0x87, 0xd4, 0x56, 0x02, 0x75, 0x65, 0x6e, 0xdc, 0xdc, 0x74,
	0x94, 0x46, 0x8d, 0xd7, 0xc1, 0x9e, 0x14, 0xf8, 0xef, 0x91, 0x1d, 0x7b, 0x37, 0x1c, 0x96, 0xc7,
	0xcd, 0x5f, 0x32, 0xf3, 0xfb, 0x3c, 0x0f, 0xc3, 0x51, 0x7b, 0xfb, 0xb6, 0x54, 0x6b, 0xd2, 0xa2,
	0xa4, 0x65, 0xab, 0x15, 0xa9, 0x0c, 0xca, 0x7b, 0x51, 0xaf, 0xa5, 0x78, 0x40, 0xcd, 0xde, 0xc3,
	0xfe, 0xa9, 0xae, 0x56, 0xa2, 0xd6, 0xd9, 0x14, 0xe2, 0x07, 0xfc, 0x59, 0x44, 0xf3, 0x68, 0x71,
	0xc0, 0xed, 0x31, 0xcb, 0x21, 0x79, 0x14, 0x4d, 0x87, 0xc5, 0x93, 0x79, 0xb4, 0x98, 0xf0, 0x5e,
	0xb0, 0x13, 0x48, 0xcf, 0x45, 0xd3, 0x9c, 0xea, 0xca, 0x64, 0x6f, 0x60, 0x24, 0x74, 0x65, 0x8a,
	0x68, 0x1e, 0x2f, 0xc6, 0xc7, 0xb3, 0xe5, 0x96, 0xbc, 0xf4, 0x58, 0xee, 0x02, 0xd8, 0x07, 0x80,
	0x55, 0x47, 0x1c, 0xbf, 0x75, 0x68, 0x68, 0x68, 0x35, 0xf9, 0x93, 0xd5, 0x21, 0x8c, 0x5d, 0x96,
	0x69, 0xd5, 0xda, 0x20, 0x7b, 0x09, 0x70, 0x89, 0xbb, 0x21, 0xec, 0x35, 0x8c, 0xdd, 0xff, 0x3e,
	0x7c, 0xcb, 0x8c, 0x86, 0xcc, 0x57, 0x70, 0x78, 0x81, 0x0d, 0x12, 0xee, 0xe6, 0x4c, 0xe1, 0x69,
	0x08, 0xf1, 0xce, 0x37, 0xf0, 0xec, 0x9a, 0x50, 0x0b, 0x52, 0x3a, 0xa4, 0xe5, 0x90, 0x18, 0x12,
	0x9a, 0x02, 0xdd, 0x09, 0xfb, 0xb5, 0xa9, 0x65, 0x4d, 0xa1, 0x0e, 0x27, 0xac, 0x45, 0x29, 0xda,
	0x22, 0x9e, 0x47, 0x8b, 0x84, 0xdb, 0x23, 0xfb, 0x08, 0x93, 0x00, 0xbc, 0x26, 0x94, 0xff, 0xdc,
	0x91, 0x33, 0x98, 0x6e, 0x2f, 0xe2, 0xeb, 0x5c, 0x42, 0x52, 0x13, 0xca, 0x30, 0x85, 0x62, 0x38,
	0x85, 0xa1, 0x09, 0xef, 0xc3, 0xd8, 0x0a, 0xd2, 0x4d, 0x6e, 0x06, 0xa3, 0x52, 0xdd, 0xf5, 0x2d,
	0x4a, 0xb8, 0x3b, 0x67, 0x05, 0xec, 0x4b, 0x34, 0x46, 0x54, 0xbd, 0xf7, 0x01, 0x0f, 0x32, 0x7b,
	0x0e, 0x7b, 0x1a, 0x4d, 0xd7, 0x90, 0x2b, 0x65, 0xc2, 0xbd, 0x62, 0x17, 0x30, 0xfd, 0x82, 0x74,
	0xd3, 0x51, 0xbb, 0x9d, 0xf1, 0x3b, 0x48, 0xb5, 0x77, 0x71, 0xf4, 0xf1, 0x71, 0x3e, 0xbc, 0x58,
	0xb8, 0x01, 0xdf, 0x44, 0xb1, 0x19, 0x1c, 0x0d, 0x28, 0xfe, 0x63, 0x0e, 0xd9, 0x25, 0x52, 0x58,
	0x38, 0x0f, 0xb7, 0x43, 0xfc, 0xa4, 0xaa, 0xcf, 0xa6, 0x1a, 0x0c, 0x51, 0x9a, 0x2a, 0x2c, 0xaf,
	0x34, 0x95, 0x1d, 0x62, 0x08, 0xf1, 0x28, 0x0d, 0xb3, 0x73, 0xff, 0x12, 0x2c, 0x2f, 0xa4, 0xbe,
	0x80, 0x34, 0x3c, 0x10, 0x9f, 0xbf, 0xd1, 0xb6, 0x60, 0x89, 0x74, 0xaf, 0xee, 0x7c, 0x27, 0xbc,
	0xda, 0xec, 0x7d, 0xfc, 0xb7, 0xbd, 0xbf, 0x82, 0xfc, 0x77, 0x4f, 0xdf, 0xf7, 0xff, 0xee, 0xce,
	0x59, 0x7a, 0x15, 0x7f, 0x1d, 0x7d, 0xff, 0xf1, 0x28, 0x6f, 0xf7, 0xdc, 0x33, 0x3e, 0xf9, 0x15,
	0x00, 0x00, 0xff, 0xff, 0x40, 0xc0, 0x0e, 0x67, 0xdb, 0x03, 0x00, 0x00,
}
